test_name: GSE68559_sub

raw_counts_script: "config/input_scripts/GSE68559_sub.jl"
entrez_match_file: "data/GSE68559/matching_entrez_ids.txt"
distributed: true
conditions:
  region: ##numbers match those in the column titles (from GSE- RAW) . 
    frontopolar cortex: [9,18,27,36,45,54,63,72,80,89] #1
    Wernicke's area: [10,19,28,37,46,55,64,73,81,90] #2
    anterior cingulate cortex: [11,20,29,38,47,56,65,74,82,91] #3
    insula: [12,21,30,39,48,57,66,75,83,92] #4
    amygdala: [13,22,31,40,49,58,67,76,84,93] #5
    hippocampus: [14,23,32,41,50,59,68,77,85,94] #6
    posterior putamen: [15,24,33,42,51,60,69,78,86,95] #7
    cerebellum: [16,25,34,43,52,61,70,79,87,96] #8
    raphae nuclei: [17,26,35,44,53,62,71,88,97] #9
    dorsolateral prefrontal cortex: [1,2,3,4,5,6,7,8] #10
  patient: ## notice strange order for the single digit samples-- this it to place 10th region samples last not first
    MB011: [9,10,11,12,13,14,15,16,17,1] #smoker
    MB052: [18,19,20,21,22,23,24,25,26,2] #nonsmoker
    MB059: [27,28,29,30,31,32,33,34,35] #smoker
    MB100: [36,37,38,39,40,41,42,43,44,3] #smoker
    MB147: [45,46,47,48,49,50,51,52,53,4] #nonsmoker
    MB148: [54,55,56,57,58,59,60,61,62,5] #smoker
    MB151: [63,64,65,66,67,68,69,70,71,6] #nonsmoker
    MB160: [72,73,74,75,76,77,78,79] #smoker (note, this is where the one sample was removed- for region 10)
    MB197: [80,81,82,83,84,85,86,87,88,7] #nonsmoker
    MB202: [89,90,91,92,93,94,95,96,97,8] #nonsmoker
  treatment: ##we maintain the same ordering here, combining all smoker subjects in the same order as they would be separately
    smoker: [9,10,11,12,13,14,15,16,17,1,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,3,54,55,56,57,58,59,60,61,62,5,72,73,74,75,76,77,78,79] 
    nonsmoker: [18,19,20,21,22,23,24,25,26,2,45,46,47,48,49,50,51,52,53,4,63,64,65,66,67,68,69,70,71,6,80,81,82,83,84,85,86,87,88,7,89,90,91,92,93,94,95,96,97,8]

cache:
  keep_cache: true
  base_dir: "output/cache"
  clear:
    archive: false
    test_dir: false
    round_dir: false
    vst_dir: false
    clean_dir: false 
    norm_dir: false
    prune_dir: false
    sampling_dir: false 
    similarity_dir: false 
    adjacency_dir: false  
    anal_dir: false 
    bio_dir: false
    community_dir: false 
    wgcna_dir: false
    graphlet_counting_dir: false
    rep_dir: false 
    graphlet_enum_dir: false 
    coinc_dir: false 
    orbit_dir: false 

website:
  website: false
  page_name: "menu1"
  website_dir: "website"

data_preprocessing: 
  roundsig: 5 
  vst: true
  expression_cutoff: 0.10
  minreq: 0.10
  clean_method: "per-sample"
  norm_method: "upper_quartile"
  prune: false
  prune_condition: "strain"
  prune_cutoff: 2.0
  prune_strictness: "n-1"
  sample_method: "cutoff"
  variance_percent: 1.0
    
network_construction:
  construct: true
  coexpression: "pidc"
  nbins: "sqrt_n"  
  threshold: 0.95
  threshold_method: "empirical_dist_zero"
  visualise: false
  synthetic: false

analysis:    
  biological_validation: true
  species: "hsa"  
  community_detection: true
  wgcna: true
  func_annotate: false
  graphlet_counting: true
  graphlet_size: 4
  recursive: true #count lower graphlets as well
  typed_representation: true
  null_model_size: 1000
  coincident_graphlets: false
  coincident_terms: "KEGG"

  
